// (C) Copyright 2025, SECO Mind Srl
//
// SPDX-License-Identifier: Apache-2.0

#ifndef GRPC_CONVERTER_H
#define GRPC_CONVERTER_H

/**
 * @file private/grpc/grpc_converter.hpp
 * @brief Type conversion utilities between Astarte SDK and gRPC Protobuf types.
 *
 * @details This file defines functor classes used to convert data types defined
 * in the Astarte C++ SDK (like `Data`, `DatastreamObject`) to and from their
 * corresponding Protobuf representations generated by the gRPC compiler.
 */

#include <astarteplatform/msghub/astarte_data.pb.h>
#include <astarteplatform/msghub/astarte_message.pb.h>
#include <astarteplatform/msghub/interface.pb.h>
#include <astarteplatform/msghub/property.pb.h>

#include <chrono>
#include <cstdint>
#include <list>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "astarte_device_sdk/data.hpp"
#include "astarte_device_sdk/errors.hpp"
#include "astarte_device_sdk/individual.hpp"
#include "astarte_device_sdk/msg.hpp"
#include "astarte_device_sdk/object.hpp"
#include "astarte_device_sdk/ownership.hpp"
#include "astarte_device_sdk/property.hpp"
#include "astarte_device_sdk/stored_property.hpp"

namespace astarte::device::grpc {

using gRPCAstarteData = astarteplatform::msghub::AstarteData;
using gRPCAstarteDatastreamIndividual = astarteplatform::msghub::AstarteDatastreamIndividual;
using gRPCAstarteDatastreamObject = astarteplatform::msghub::AstarteDatastreamObject;
using gRPCAstartePropertyIndividual = astarteplatform::msghub::AstartePropertyIndividual;
using gRPCAstarteMessage = astarteplatform::msghub::AstarteMessage;
using gRPCStoredProperties = astarteplatform::msghub::StoredProperties;
using gRPCOwnership = astarteplatform::msghub::Ownership;

/**
 * @brief Functor for converting C++ types to Astarte Protobuf messages.
 *
 * @details This class provides overloaded operators to convert standard C++ types
 * and SDK specific types (like `Data`) into unique pointers of Protobuf messages.
 */
class GrpcConverterTo {
 public:
  auto operator()(int32_t value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(int64_t value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(double value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(bool value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::string& value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<uint8_t>& value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(std::chrono::system_clock::time_point value) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<int32_t>& values) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<int64_t>& values) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<double>& values) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<bool>& values) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<std::string>& values) -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<std::vector<uint8_t>>& values)
      -> std::unique_ptr<gRPCAstarteData>;
  auto operator()(const std::vector<std::chrono::system_clock::time_point>& values)
      -> std::unique_ptr<gRPCAstarteData>;

  /**
   * @brief Converts a Data object to a Datastream Individual Protobuf message.
   * @param[in] value The data value.
   * @param[in] timestamp Optional timestamp.
   * @return A unique_ptr to the constructed AstarteDatastreamIndividual message.
   */
  auto operator()(const Data& value, const std::chrono::system_clock::time_point* timestamp)
      -> std::unique_ptr<gRPCAstarteDatastreamIndividual>;

  /**
   * @brief Converts a DatastreamObject to a Datastream Object Protobuf message.
   * @param[in] value The object data.
   * @param[in] timestamp Optional timestamp.
   * @return A unique_ptr to the constructed AstarteDatastreamObject message.
   */
  auto operator()(const DatastreamObject& value,
                  const std::chrono::system_clock::time_point* timestamp)
      -> std::unique_ptr<gRPCAstarteDatastreamObject>;

  /**
   * @brief Converts an optional Data object to a Property Individual Protobuf message.
   * @param[in] value The property data (nullopt for unset).
   * @return A unique_ptr to the constructed AstartePropertyIndividual message.
   */
  auto operator()(const std::optional<Data>& value)
      -> std::unique_ptr<gRPCAstartePropertyIndividual>;
};

/**
 * @brief Functor for converting Astarte Protobuf messages to C++ SDK types.
 *
 * @details This class provides overloaded operators to parse Protobuf messages
 * received from the gRPC interface back into SDK native types like `Data`, `Message`,
 * or `StoredProperty`.
 */
class GrpcConverterFrom {
 public:
  /**
   * @brief Converts an AstarteData Protobuf message to a Data object.
   * @param[in] value The Protobuf message.
   * @return An expected containing the Data on success or Error on failure.
   */
  auto operator()(const gRPCAstarteData& value) -> astarte_tl::expected<Data, Error>;

  /**
   * @brief Converts an AstarteDatastreamIndividual Protobuf message to a DatastreamIndividual.
   * @param[in] value The Protobuf message.
   * @return An expected containing the DatastreamIndividual on success or Error on failure.
   */
  auto operator()(const gRPCAstarteDatastreamIndividual& value)
      -> astarte_tl::expected<DatastreamIndividual, Error>;

  /**
   * @brief Converts an AstarteDatastreamObject Protobuf message to a DatastreamObject.
   * @param[in] value The Protobuf message.
   * @return An expected containing the DatastreamObject on success or Error on failure.
   */
  auto operator()(const gRPCAstarteDatastreamObject& value)
      -> astarte_tl::expected<DatastreamObject, Error>;

  /**
   * @brief Converts an AstartePropertyIndividual Protobuf message to a PropertyIndividual.
   * @param[in] value The Protobuf message.
   * @return An expected containing the PropertyIndividual on success or Error on failure.
   */
  auto operator()(const gRPCAstartePropertyIndividual& value)
      -> astarte_tl::expected<PropertyIndividual, Error>;

  /**
   * @brief Converts a generic AstarteMessage Protobuf message to a Message object.
   * @param[in] value The Protobuf message.
   * @return An expected containing the Message on success or Error on failure.
   */
  auto operator()(const gRPCAstarteMessage& value) -> astarte_tl::expected<Message, Error>;

  /**
   * @brief Converts a Protobuf ownership enum to an SDK Ownership enum.
   * @param[in] value The Protobuf ownership value.
   * @return The corresponding SDK Ownership value.
   */
  auto operator()(const gRPCOwnership& value) -> Ownership;

  /**
   * @brief Converts a StoredProperties Protobuf message to a list of StoredProperty objects.
   * @param[in] value The Protobuf message containing the list.
   * @return An expected containing the list of StoredProperty on success or Error on failure.
   */
  auto operator()(const gRPCStoredProperties& value)
      -> astarte_tl::expected<std::list<StoredProperty>, Error>;
};

}  // namespace astarte::device::grpc

#endif  // GRPC_CONVERTER_H
