# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: End to end tests

on:
  pull_request:
  push:
    branches:
      - main
      - release-*

env:
  RUST_LOG: debug

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    concurrency:
      group: end-to-end-test-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        msghub-version: ["v0.8.0"]
        grpc-version: ["1.69.0"]
    steps:
      - name: Checkout C++ client
        uses: actions/checkout@v5
        with:
          path: astarte-device-sdk-cpp
      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
          use_venv: true
      - name: Create Astarte Cluster
        uses: astarte-platform/astarte-cluster-action@v1
        with:
          astarte_version: "1.2.0"
      - name: Install interfaces
        working-directory: ./astarte-device-sdk-cpp/.github/workflows
        timeout-minutes: 3
        run: ./install_interfaces.sh $GITHUB_WORKSPACE/astarte-device-sdk-cpp/end_to_end/interfaces
      - name: Register a device new device
        run: |
          APPENGINE_TOKEN=$(astartectl utils gen-jwt appengine)
          DEVICE_ID=$(astartectl utils device-id generate-random)
          CREDENTIALS_SECRET=$(astartectl pairing agent register --compact-output -- "$DEVICE_ID")
          echo "E2E_REALM=test" >> $GITHUB_ENV
          echo "E2E_APPENGINE_TOKEN=$APPENGINE_TOKEN" >> $GITHUB_ENV
          echo "E2E_APPENGINE_URL=https://api.autotest.astarte-platform.org/appengine" >> $GITHUB_ENV
          echo "E2E_PAIRING_URL=https://api.autotest.astarte-platform.org/pairing" >> $GITHUB_ENV
          echo "E2E_DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
          echo "E2E_CREDENTIALS_SECRET=$CREDENTIALS_SECRET" >> $GITHUB_ENV
      - name: Checkout message hub
        uses: actions/checkout@v5
        with:
          repository: astarte-platform/astarte-message-hub
          path: astarte-message-hub
          ref: ${{ matrix.msghub-version }}
      - name: Fill in message hub config
        working-directory: ./astarte-message-hub
        run: |
          echo "realm = \"$E2E_REALM\"" > message-hub-config.toml
          echo "pairing_url = \"$E2E_PAIRING_URL\"" >> message-hub-config.toml
          echo "grpc_socket_port = 50051" >> message-hub-config.toml
          echo "device_id = \"$E2E_DEVICE_ID\"" >> message-hub-config.toml
          echo "credentials_secret = \"$E2E_CREDENTIALS_SECRET\"" >> message-hub-config.toml
          echo "store_directory = \"./tmp\"" >> message-hub-config.toml
          cat message-hub-config.toml
      - name: Create folder for message hub binary
        run: |
          mkdir ./astarte-message-hub/target
          mkdir ./astarte-message-hub/target/release
      - name: Restore cached astarte-message-hub binary
        id: cache-astarte-message-hub-restore
        uses: actions/cache/restore@v4
        with:
          path: ./astarte-message-hub/target/release/astarte-message-hub
          key: astarte-message-hub-${{ matrix.msghub-version }}
      - name: Build message hub
        if: steps.cache-astarte-message-hub-restore.outputs.cache-hit != 'true'
        run: cargo build --release
        working-directory: ./astarte-message-hub
      - name: Save message hub binary
        if: steps.cache-astarte-message-hub-restore.outputs.cache-hit != 'true'
        id: cache-astarte-message-hub-save
        uses: actions/cache/save@v4
        with:
          path: ./astarte-message-hub/target/release/astarte-message-hub
          key: ${{ steps.cache-astarte-message-hub-restore.outputs.cache-primary-key }}
      - name: Run message hub
        working-directory: ./astarte-message-hub
        run: nohup ./target/release/astarte-message-hub > nohup.out 2> nohup.err < /dev/null &
      - name: Fill in C++ client config
        working-directory: ./astarte-device-sdk-cpp/end_to_end
        run: |
          echo "server_addr = \"localhost:50051\"" > config.toml
          echo "node_id = \"aa04dade-9401-4c37-8c6a-d8da15b083ae\"" >> config.toml
          echo "realm = \"$E2E_REALM\"" >> config.toml
          echo "appengine_url = \"$E2E_APPENGINE_URL\"" >> config.toml
          echo "appengine_token = \"$E2E_APPENGINE_TOKEN\"" >> config.toml
          echo "device_id = \"$E2E_DEVICE_ID\"" >> config.toml
          cat config.toml
      - name: Build the end to end tests
        working-directory: ./astarte-device-sdk-cpp
        run: ./end_to_end.sh --fresh --ext-tools
      - name: Run the end to end tests
        working-directory: ./astarte-device-sdk-cpp
        run: ./end_to_end/build/app
      - name: Install valgrind
        working-directory: ./astarte-device-sdk-cpp
        run: |
          sudo apt update
          sudo apt install valgrind
      - name: Run the end to end tests with valgrind
        working-directory: ./astarte-device-sdk-cpp
        run: valgrind --leak-check=summary --track-origins=no --error-exitcode=1 ./end_to_end/build/app
